# filepath: d:\Jupyter_notebook\study\VisionBaseline\config.yaml
model: vgg16_advanced
img_size: 224
img_channels: 3
num_epochs: 100
num_epochs_decay: 10
early_stopping_rounds: 10
lr_decay: 0.0001
lr: 0.01
batch_size: 4
optim: SGD
num_class: 102
drop_rate: 0.5
dataset_path: "D:\\Jupyter_notebook\\study\\VisionDatasets\\flowers-102/jpg"
dataset_target_path: "D:\\Jupyter_notebook\\study\\VisionDatasets\\flowers-102/imagelabels.mat"
split_dataset_id: "D:\\Jupyter_notebook\\study\\VisionDatasets\\flowers-102/setid.mat"
save_state_path: "runs"
weight_decay: 0.0001
loss_function: "CE"  # BCE, CE, FOCAL
focal_loss_gamma: 2.0
focal_loss_alpha: 0.25